name: example
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - '**/*.tf'
  workflow_dispatch:

env:
  TF_VERSION: 1.4.1
  AWS_REGION: ap-northeast-1
jobs:
  deploy:
    name: deploy VPC
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: /infra/env/develop
    steps:
      - name: Chekcout repository
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1' # リージョンを指定
          role-to-assume: 'arn:aws:iam::393506046639:role/test-terraform-github-role' # 作成した IAM ロールの ARN

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.TF_VERSION }}
      - name: init
        run: terraform init
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform plan
        run: terraform plan -no-color
